// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAQp4iYKQnQoMWvys1WyWkxR1FsA-15CY',
    appId: '1:576996108646:web:1db0c4501413ed9f8c80a7',
    messagingSenderId: '576996108646',
    projectId: 'book-d21ec',
    authDomain: 'book-d21ec.firebaseapp.com',
    storageBucket: 'book-d21ec.appspot.com',
    measurementId: 'G-X47RH2MYMT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfktA_3dMNAwfjkm3H9LBebSYTvSBe3HA',
    appId: '1:576996108646:android:4965ba7276e4ab748c80a7',
    messagingSenderId: '576996108646',
    projectId: 'book-d21ec',
    storageBucket: 'book-d21ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEy1peUHoIZPg8WMZv2EmIwg3QYZAe_A8',
    appId: '1:576996108646:ios:a9d4a3c724ab80b38c80a7',
    messagingSenderId: '576996108646',
    projectId: 'book-d21ec',
    storageBucket: 'book-d21ec.appspot.com',
    iosBundleId: 'com.example.book',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEy1peUHoIZPg8WMZv2EmIwg3QYZAe_A8',
    appId: '1:576996108646:ios:a9d4a3c724ab80b38c80a7',
    messagingSenderId: '576996108646',
    projectId: 'book-d21ec',
    storageBucket: 'book-d21ec.appspot.com',
    iosBundleId: 'com.example.book',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAQp4iYKQnQoMWvys1WyWkxR1FsA-15CY',
    appId: '1:576996108646:web:cae8d3cb770cfb608c80a7',
    messagingSenderId: '576996108646',
    projectId: 'book-d21ec',
    authDomain: 'book-d21ec.firebaseapp.com',
    storageBucket: 'book-d21ec.appspot.com',
    measurementId: 'G-0L44HYBWK5',
  );
}
